CONFIG_NUMBER: 1
CUDA: false
ENT_COEF: 0.01
GAMMA: 0.99
LEARNING_RATE: 0.0001
LR_SCHEDULING: "Linear"
MAX_EPISODE_LENGTH: 12000
NB_ENVS: 4
NB_FRAMES: 4
NB_STEPS: 256
OBSERVATION_SIZE: 84
SEED: 2307
TOTAL_TIMESTEPS: 2000000