_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.10.7
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
CONFIG_NUMBER:
    value: 7
CUDA:
    value: false
ENT_COEF:
    value: 0.1
GAMMA:
    value: 0.99
LEARNING_RATE:
    value: 0.0001
LR_SCHEDULING:
    value: Linear
MAX_EPISODE_LENGTH:
    value: 12000
NB_ENVS:
    value: 12
NB_FRAMES:
    value: 4
NB_STEPS:
    value: 512
OBSERVATION_SIZE:
    value: 64
SEED:
    value: 2307
TOTAL_TIMESTEPS:
    value: 2e+06
VF_COEF:
    value: 0.5
