# Hyperparam ref: https://huggingface.co/sb3/ppo_lstm-CarRacing-v0

hyperparams:
  batch_size: 128
  clip_range: 0.2
  ent_coef: 0.0
  gae_lambda: 0.95
  gamma: 0.99
  learning_rate:
    schedule: linear
    initial: 0.0001
  max_grad_norm: 0.5
  n_epochs: 10
  n_steps: 512
  sde_sample_freq: 4
  use_sde: true
  vf_coef: 0.5

policy_kwargs:
  log_std_init: -2
  ortho_init: false
  enable_critic_lstm: false
  activation_fn: GELU
  lstm_hidden_size: 128

transformation:
  resize_observation: [64, 64]
  grayscale_observation:
    keep_dim: true
  n_envs: 8
  frame_stack: 2
  normalize:
    norm_reward: true
    norm_obs: false

total_timesteps: 2000000